export default {
    
    subs: [
        { id: 1, name: 'カーリングボム' },
        { id: 2, name: 'キューバンボム' },
        { id: 3, name: 'クイックボム' },
        { id: 4, name: 'スプラッシュボム' },
        { id: 5, name: 'タンサンボム' },
        { id: 6, name: 'ロボットボム' },
        { id: 7, name: 'トーピード' },
        { id: 8, name: 'ジャンプビーコン' },
        { id: 9, name: 'スプラッシュシールド' },
        { id: 10, name: 'トラップ' },
        { id: 11, name: 'ポイズンミスト' },
        { id: 12, name: 'ポイントセンサー' },
        { id: 13, name: 'ラインマーカー' },
        { id: 14, name: 'スプリンクラー' },
    ],

    specials: [
        { id: 1, name: 'ウルトラショット' },
        { id: 2, name: 'ウルトラハンコ' },
        { id: 3, name: 'カニタンク' },
        { id: 4, name: 'サメライド' },
        { id: 5, name: 'ジェットパック' },
        { id: 6, name: 'トリプルトルネード' },
        { id: 7, name: 'ナイスダマ' },
        { id: 8, name: 'マルチミサイル' },
        { id: 9, name: 'ショクワンダー' },
        { id: 10, name: 'アメフラシ' },
        { id: 11, name: 'キューインキ' },
        { id: 12, name: 'ホップソナー' },
        { id: 13, name: 'メガホンレーザー5.1ch' },
        { id: 14, name: 'エナジースタンド' },
        { id: 15, name: 'グレートバリア' },
    ],

    type: [
        { id: 1, name: 'シューター' },
        { id: 2, name: 'ブラスター' },
        { id: 3, name: 'チャージャー' },
        { id: 4, name: 'スロッシャー' },
        { id: 5, name: 'スピナー' },
        { id: 6, name: 'マニューバー' },
        { id: 7, name: 'シェルター' },
        { id: 8, name: 'ストリンガー' },
        { id: 9, name: 'フロッシャー' },
        { id: 10, name: 'ワイパー' },
        { id: 11, name: 'ローラー' },
        { id: 12, name: 'フデ' },
    ],

    weapons: [
        {id: 1, name: 'スプラシューター', typeId: 1, subId: 2, specialId: 1},
        {id: 2, name: 'スプラローラー', typeId: 11, subId: 1, specialId: 15},
        {id: 3, name: 'スプラチャージャー', typeId: 3, subId: 4, specialId: 11},
        {id: 4, name: 'ホットブラスター', typeId: 2, subId: 6, specialId: 15},
        {id: 5, name: 'バケットスロッシャー', typeId: 4, subId: 4, specialId: 6},
        {id: 6, name: 'スプラマニューバー', typeId: 6, subId: 2, specialId: 3},
        {id: 7, name: 'ホクサイ', typeId: 12, subId: 2, specialId: 9},
        {id: 8, name: 'バレルスピナー', typeId: 5, subId: 14, specialId: 12},
        {id: 9, name: 'トライストリンガー', typeId: 8, subId: 11, specialId: 13},
        {id: 10, name: 'プロモデラーMG', typeId: 1, subId: 5, specialId: 4},
        {id: 11, name: 'パラシェルター', typeId: 7, subId: 14, specialId: 6},
        {id: 12, name: 'ドライブワイパー', typeId: 10, subId: 7, specialId: 2},
        {id: 13, name: 'N-ZAP85', typeId: 1, subId: 2, specialId: 14},
        {id: 14, name: 'カーボンローラー', typeId: 11, subId: 6, specialId: 9},
        {id: 15, name: 'ラピッドブラスター', typeId: 2, subId: 10, specialId: 6},
        {id: 16, name: 'パブロ', typeId: 12, subId: 4, specialId: 13},
        {id: 17, name: 'スクイックリンα', typeId: 3, subId: 12, specialId: 15},
        {id: 18, name: 'デュアルスイーパー', typeId: 6, subId: 4, specialId: 12},
        {id: 19, name: 'ボールドマーカー', typeId: 1, subId: 1, specialId: 2},
        {id: 20, name: 'プライムシューター', typeId: 1, subId: 13, specialId: 3},
        {id: 21, name: 'スプラスコープ', typeId: 3, subId: 4, specialId: 11},
        {id: 22, name: 'ヒッセン', typeId: 4, subId: 11, specialId: 5},
        {id: 23, name: 'LACT-450', typeId: 8, subId: 1, specialId: 8},
        {id: 24, name: '.52ガロン', typeId: 1, subId: 9, specialId: 13},
        {id: 25, name: 'ロングブラスター', typeId: 2, subId: 2, specialId: 12},
        {id: 26, name: 'ダイナモローラー', typeId: 11, subId: 14, specialId: 14},
        {id: 27, name: 'スプラスピナー', typeId: 5, subId: 3, specialId: 2},
        {id: 28, name: 'ノヴァブラスター', typeId: 2, subId: 4, specialId: 9},
        {id: 29, name: 'L3リールガン', typeId: 1, subId: 1, specialId: 3},
        {id: 30, name: 'スクリュースロッシャー', typeId: 4, subId: 5, specialId: 7},
        {id: 31, name: 'スパッタリー', typeId: 6, subId: 8, specialId: 14},
        {id: 32, name: 'ジェットスイーパー', typeId: 1, subId: 13, specialId: 11},
        {id: 33, name: 'ジムワイパー', typeId: 10, subId: 3, specialId: 9},
        {id: 34, name: 'シャープマーカー', typeId: 1, subId: 3, specialId: 3},
        {id: 35, name: 'キャンピングシェルター', typeId: 7, subId: 8, specialId: 11},
        {id: 36, name: '.96ガロン', typeId: 1, subId: 14, specialId: 11},
        {id: 37, name: 'クアッドホッパーブラック', typeId: 6, subId: 6, specialId: 4},
        {id: 38, name: 'リッター4K', typeId: 3, subId: 10, specialId: 12},
        {id: 39, name: 'スパイガジェット', typeId: 7, subId: 10, specialId: 4},
        {id: 40, name: 'ボトルガイザー', typeId: 1, subId: 9, specialId: 1},
        {id: 41, name: 'オーバーフロッシャー', typeId: 9, subId: 14, specialId: 10},
        {id: 42, name: 'ヴァリアブルローラー', typeId: 11, subId: 10, specialId: 8},
        {id: 43, name: 'ハイドラント', typeId: 5, subId: 6, specialId: 7},
        {id: 44, name: 'ケルビン525', typeId: 6, subId: 9, specialId: 7},
        {id: 45, name: 'クラッシュブラスター', typeId: 2, subId: 4, specialId: 1},
        {id: 46, name: '14式竹筒銃・甲', typeId: 3, subId: 6, specialId: 13},
        {id: 47, name: 'H3リールガン', typeId: 1, subId: 12, specialId: 14},
        {id: 48, name: 'ソイチューバー', typeId: 3, subId: 7, specialId: 8},
        {id: 49, name: 'Rブラスターエリート', typeId: 2, subId: 11, specialId: 11},
        {id: 50, name: '4Kスコープ', typeId: 3, subId: 10, specialId: 12},
        {id: 51, name: 'ノーチラス47', typeId: 5, subId: 12, specialId: 10},
        {id: 52, name: 'エクスプロッシャー', typeId: 4, subId: 12, specialId: 10},
        {id: 53, name: 'クーゲルシュライバー', typeId: 5, subId: 5, specialId: 5},
    ],
};